spring:
  datasource:
    url: jdbc:h2:file:./out/itunes.db
    username: dev
    password: dev
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog.yaml
  application:
    name: itunes